name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish release'
        required: false
        default: false
        type: boolean

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Debug environment (Windows)
      if: runner.os == 'Windows'
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "CSC_IDENTITY_AUTO_DISCOVERY: ${{ env.CSC_IDENTITY_AUTO_DISCOVERY }}"
        echo "Checking custom_win_sign.js..."
        if (Test-Path "custom_win_sign.js") { echo "custom_win_sign.js exists" } else { echo "custom_win_sign.js not found" }
      shell: powershell

    - name: Build for Windows
      run: npm run package
      env:
        NODE_ENV: production
        CSC_IDENTITY_AUTO_DISCOVERY: false

    - name: Upload Windows artifacts
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: |
          dist/*.exe
          dist/*.msi
        retention-days: 30

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Install additional macOS build dependencies
      run: |
        # Install dmg-license if it's missing (this can happen in some CI environments)
        if ! npm list dmg-license > /dev/null 2>&1; then
          echo "Installing dmg-license..."
          npm install dmg-license --save-optional || echo "dmg-license installation failed, continuing..."
        fi
      continue-on-error: true

    - name: Debug environment (macOS)
      run: |
        echo "Node version: $(node --version)"
        echo "NPM version: $(npm --version)"
        echo "CSC_IDENTITY_AUTO_DISCOVERY: $CSC_IDENTITY_AUTO_DISCOVERY"
        echo "Platform: $(uname -s)"
        echo "Architecture: $(uname -m)"
        ls -la | grep -E "(custom_|sign|\.p12|\.pem)" || echo "No signing files found"
        echo "Checking electron-builder dependencies..."
        npm list electron-builder dmg-builder 2>/dev/null || echo "Some packages not found (this may be normal)"

    - name: Build for macOS
      run: npm run package
      env:
        NODE_ENV: production
        CSC_IDENTITY_AUTO_DISCOVERY: false

    - name: Upload macOS artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: |
          dist/*.dmg
          dist/*.zip
        retention-days: 30

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: '.node-version'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build for Linux
      run: npm run package
      env:
        NODE_ENV: production
        CSC_IDENTITY_AUTO_DISCOVERY: false

    - name: Upload Linux artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: |
          dist/*.AppImage
          dist/*.deb
          dist/*.rpm
        retention-days: 30

  # Cross-platform build removed due to platform-specific dependency issues
  # Individual platform builds above provide better compatibility and reliability

  create-release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-linux]
    if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && github.event.inputs.publish == 'true')

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download Windows artifacts
      uses: actions/download-artifact@v4
      with:
        name: windows-build
        path: dist/

    - name: Download macOS artifacts
      uses: actions/download-artifact@v4
      with:
        name: macos-build
        path: dist/

    - name: Download Linux artifacts
      uses: actions/download-artifact@v4
      with:
        name: linux-build
        path: dist/

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        draft: false
        prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') }}
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
